"""Small dependency-free browser dashboard for local and container deployments."""
from fastapi.responses import HTMLResponse


def dashboard() -> HTMLResponse:
    return HTMLResponse("""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fraud Intelligence Console</title><style>
:root{--ink:#e8eefc;--muted:#a6b4ce;--bg:#0a1020;--panel:#121b31;--line:#263756;--accent:#6ae4c8;--warn:#ffd166;--danger:#ff6b7a}.wrap{max-width:1100px;margin:auto;padding:34px 20px;font-family:Inter,Segoe UI,Arial,sans-serif;color:var(--ink)}body{margin:0;background:linear-gradient(135deg,#091021,#101b36)}h1{font-size:2.15rem;margin:.2rem 0}.sub{color:var(--muted);max-width:760px}.panel{background:rgba(18,27,49,.96);border:1px solid var(--line);border-radius:16px;padding:22px;margin-top:22px;box-shadow:0 18px 40px #0004}label{display:block;font-weight:700;margin:15px 0 7px}input{width:100%;box-sizing:border-box;background:#0b1327;border:1px solid var(--line);border-radius:9px;padding:12px;color:var(--ink)}button{background:var(--accent);color:#062018;border:0;border-radius:9px;padding:12px 17px;font-weight:800;cursor:pointer;margin-top:18px}.note{font-size:.88rem;color:var(--muted)}#summary{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.metric{padding:10px 13px;border-radius:10px;background:#0b1327;border:1px solid var(--line)}.card{margin-top:12px;padding:16px;border:1px solid var(--line);border-left:5px solid var(--accent);border-radius:10px;background:#0b1327}.card.flag{border-left-color:var(--danger)}.label{font-size:.78rem;color:var(--muted);letter-spacing:.06em}.status{font-weight:800;margin:5px 0}.meta{font-size:.88rem;color:var(--muted)}details{margin-top:9px}pre{white-space:pre-wrap;word-break:break-word;font-size:.75rem;color:#cbd7ee}.loading{color:var(--warn)}</style></head>
<body><main class="wrap"><h1>Fraud Intelligence Console</h1><p class="sub">Upload individual documents or choose a folder. Every file is screened independently, stored in the provenance database, and assigned a human-review triage label.</p>
<section class="panel"><form id="form"><label>Choose document images</label><input id="files" type="file" accept=".png,.jpg,.jpeg,.webp" multiple><p class="note">Select one or more PNG, JPG, JPEG, or WEBP document images.</p><label>Or choose a folder (Chrome/Edge)</label><input id="folder" type="file" accept=".png,.jpg,.jpeg,.webp" multiple webkitdirectory directory><p class="note">Use only one picker at a time. Folder selection includes supported images inside the chosen folder.</p><label>Optional shared identity key</label><input id="identity" maxlength="128" placeholder="e.g. demo-legitimate-001"><label>Analysis depth</label><select id="mode"><option value="fast" selected>Fast batch triage — deepfake deferred</option><option value="full">Full analysis — deepfake on every file</option></select><button id="submit" type="submit">Screen and flag documents</button></form><div id="summary"></div><div id="results"></div></section></main>
<script>const form=document.getElementById('form'),files=document.getElementById('files'),folder=document.getElementById('folder'),mode=document.getElementById('mode'),out=document.getElementById('results'),summary=document.getElementById('summary');
function escapeText(v){const n=document.createElement('span');n.textContent=String(v??'');return n.innerHTML}function card(r){const triage=r.triage||{label:r.status,flagged:r.status!=='LOW RISK',reason:''};const reasons=[...(r.explanation?.primary_reasons||[]),...(r.explanation?.supporting_reasons||[])].slice(0,3).join(', ')||'No material fraud signal detected';return `<article class="card ${triage.flagged?'flag':''}"><div class="label">${escapeText(r.filename||'upload')}</div><div class="status">${escapeText(triage.label)}</div><div class="meta">Risk score: ${escapeText(r.risk_score)} · ${escapeText(triage.reason)}</div><div class="meta">Evidence: ${escapeText(reasons)}</div><details><summary>Full screening evidence</summary><pre>${escapeText(JSON.stringify(r,null,2))}</pre></details></article>`}
form.addEventListener('submit',async e=>{e.preventDefault();const selected=files.files.length?files.files:folder.files;if(!selected.length){out.innerHTML='<p class="loading">Choose one or more document images, or choose a folder.</p>';return}out.innerHTML='<p class="loading">Screening documents and recording provenance…</p>';summary.innerHTML='';const data=new FormData();for(const file of selected)data.append('files',file,file.name);data.append('analysis_mode',mode.value);if(identity.value.trim())data.append('identity_key',identity.value.trim());try{const res=await fetch('/screen/batch',{method:'POST',body:data});const body=await res.json();if(!res.ok)throw new Error(body.detail||'Upload failed');const items=body.results||[];const counts=items.reduce((a,x)=>{const key=x.triage?.label||x.status||'ERROR';a[key]=(a[key]||0)+1;return a},{});summary.innerHTML=Object.entries(counts).map(([k,v])=>`<span class="metric">${escapeText(k)}: <b>${v}</b></span>`).join('');out.innerHTML=items.map(card).join('')}catch(err){out.innerHTML=`<p class="loading">${escapeText(err.message)}</p>`}});</script></body></html>""")
